import { ReactNode } from "react";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";

import BookmarkContextProvider from "@/contexts/BookmarksContextProvider";

import Search from "@/components/Search";
import Providers from "@/components/Providers";
import Navigation from "@/components/Navigation";

const outfit = Outfit({ subsets: ["latin"], weight: ["300", "500", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`lg:h-[calc(100vh_-_2rem)] lg:w-full lg:overflow-y-scroll lg:gap-4 lg:p-4 lg:justify-center lg:grid lg:grid-cols-[auto_1fr]  bg-movieDarkBlue text-white ${outfit.className}`}
      >
        <Providers>
          <div className="lg:hidden">
            <Navigation />
          </div>
          <div className="hidden lg:inline">
            <Navigation />
          </div>
          <div className="lg:h-[calc(100vh_-_2rem)] lg:w-full lg:overflow-y-scroll">
            <Search />
            <BookmarkContextProvider>{children}</BookmarkContextProvider>
          </div>
        </Providers>
      </body>
    </html>
  );
}
